### PR TITLE
[9.12.r1] Enable/fix compilation for SoC Lito and SoMC Lena

### PR DESCRIPTION
**Pull request by bartcubbins**
An addition to the previous PR https://github.com/sonyxperiadev/kernel-techpack-audio/pull/29, which fixes the compilation of codecs/drivers for this platform.

### CODE REVIEW

**Comment by oshmoun** [comment]
Why remove `export` then add it for each individual config in litoauto?

**Comment by bartcubbins** [comment]
@oshmoun yes, let's fix it in a more elegant way. give me 5 minutes

**Comment by bartcubbins** [comment]
I updated the first commit instead of blindly following the CAF changes

**Comment by kholk** [comment]
Yeah, I've really missed the q6afe commit; I didn't see that stray `#define CONFIG_SND_SOC_AWINIC_AW882XX` and thought that the code wasn't getting compiled at all.

Good catch!

`Reviewed-by: AngeloGioacchino Del Regno <angelogioacchino.delregno@somainline.org>`

**Comment by bartcubbins** [comment]
Force pushed the last commit, just fixing the bad indentation, no more changes.
Thanks for the review!

**Pull request merged**
