### PR TITLE
[9.12.r1] ASoC: update audio effects config names

### PR DESCRIPTION
**Pull request by bartcubbins**
Update audio effects config names to be more descriptive to avoid conflict with kernel config naming convention.

Change-Id: Ie4d9bd0128a9f52138b3a1b94abccc81b8432c1d

Fixes: https://github.com/sonyxperiadev/bug_tracker/issues/844

### CODE REVIEW

**Comment by bartcubbins** [comment]
@jerpelea kernel headers should be updated after this change

**Comment by MarijnS95** [comment]
Let's add `Fixes: https://github.com/sonyxperiadev/bug_tracker/issues/844` to the description :)

**Review by jerpelea — APPROVED** [review]

**Comment by MarijnS95** [comment]
Too late :/

**Comment by bartcubbins** [comment]
@MarijnS95 it's never too late:)

**Comment by MarijnS95** [comment]
Too late for the auto-close, but at least the issues are linked now. Thank you :pray:

**Pull request merged**
